/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package counselormgmtsystem.GUIprogram.AdminFrames;

import counselormgmtsystem.LoginFrame;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;

public class AdminMainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminMainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public AdminMainFrame() {
        initComponents();
        ImageIcon originalUserIcon = new ImageIcon(getClass().getResource("/images/user (1).png"));
        editInfoButton01.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png")).getImage().getScaledInstance(24, 24, Image.SCALE_SMOOTH)));
        adminPageUserIcon.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (1).png")).getImage().getScaledInstance(140, 140, Image.SCALE_SMOOTH)));
        Image rawUserImage = originalUserIcon.getImage();
        Image resizedUserImage = rawUserImage.getScaledInstance(80, 80, Image.SCALE_SMOOTH);
        userIcon.setIcon(new ImageIcon(resizedUserImage));    
//        FullNameTF.setEditable(!FullNameTF.isEditable());
        logoutButton.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log-out.png")).getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH)));
        logoutButton.addActionListener(e -> {
            LoginFrame loginFrame = new LoginFrame();
            loginFrame.setVisible(true);
            this.dispose();
        });
        
        
        FullNameTF.setEditable(false);
        editInfoButton01.addActionListener(e -> {
            boolean state = !FullNameTF.isEditable();
            FullNameTF.setEditable(state);

            // Optional: Change button text dynamically to reflect current state
            if (state) {
                editInfoButton01.setText("Lock Field");
            } else {
                editInfoButton01.setText("Unlock Field");
            }
        });
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    
    private void initComponents() {

        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        contentPanel = new javax.swing.JPanel();
        adminPageUserIcon = new javax.swing.JLabel();
        personalInformationTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        FullNameTF = new javax.swing.JTextField();
        UsernameTF = new javax.swing.JTextField();
        EmailTF = new javax.swing.JTextField();
        OffTF = new javax.swing.JTextField();
        ContactTF = new javax.swing.JTextField();
        editInfoButton02 = new javax.swing.JButton();
        editInfoButton01 = new javax.swing.JButton();
        editInfoButton03 = new javax.swing.JButton();
        editInfoButton05 = new javax.swing.JButton();
        editInfoButton04 = new javax.swing.JButton();
        sidebarPanel = new javax.swing.JPanel();
        profileHeader = new javax.swing.JPanel();
        userIcon = new javax.swing.JLabel();
        usernameText = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        navItem01 = new javax.swing.JPanel();
        navItemText01 = new javax.swing.JLabel();
        navItem02 = new javax.swing.JPanel();
        navItemText02 = new javax.swing.JLabel();
        navItem03 = new javax.swing.JPanel();
        navItemText03 = new javax.swing.JLabel();
        navItem04 = new javax.swing.JPanel();
        navItemText04 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));

        adminPageUserIcon.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        adminPageUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (1).png"))); // NOI18N

        personalInformationTitle.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        personalInformationTitle.setForeground(new java.awt.Color(0, 0, 0));
        personalInformationTitle.setText("Personal Information");

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Full Name: ");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Username: ");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Email: ");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Office Room: ");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("<html>Contact Number: </html>");

        FullNameTF.setText("jTextField1");
        FullNameTF.addActionListener(this::FullNameTFActionPerformed);

        UsernameTF.setText("jTextField2");
        UsernameTF.addActionListener(this::UsernameTFActionPerformed);

        EmailTF.setText("jTextField3");
        EmailTF.addActionListener(this::EmailTFActionPerformed);

        OffTF.setText("jTextField4");
        OffTF.addActionListener(this::OffTFActionPerformed);

        ContactTF.setText("jTextField5");

        editInfoButton02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N

        editInfoButton01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        editInfoButton01.setBorder(null);
        editInfoButton01.setBorderPainted(false);
        editInfoButton01.setContentAreaFilled(false);
        editInfoButton01.addActionListener(this::editInfoButton01ActionPerformed);

        editInfoButton03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        editInfoButton03.addActionListener(this::editInfoButton03ActionPerformed);

        editInfoButton05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        editInfoButton05.addActionListener(this::editInfoButton05ActionPerformed);

        editInfoButton04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        editInfoButton04.addActionListener(this::editInfoButton04ActionPerformed);

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(personalInformationTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210))
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contentPanelLayout.createSequentialGroup()
                                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(contentPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(8, 8, 8)
                                        .addComponent(FullNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                                    .addGroup(contentPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(UsernameTF)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(editInfoButton01, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(editInfoButton02, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(contentPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)))
                                .addGap(6, 6, 6))
                            .addGroup(contentPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(adminPageUserIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentPanelLayout.createSequentialGroup()
                                .addComponent(ContactTF, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(editInfoButton05, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contentPanelLayout.createSequentialGroup()
                                .addComponent(OffTF, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(editInfoButton04, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(37, 37, 37)
                        .addComponent(EmailTF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editInfoButton03, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(386, 386, 386))))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(personalInformationTitle)
                .addGap(32, 32, 32)
                .addComponent(adminPageUserIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(OffTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(editInfoButton04, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editInfoButton05, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContactTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editInfoButton01, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(FullNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentPanelLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(UsernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(contentPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editInfoButton02, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(78, 78, 78)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editInfoButton03, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EmailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addContainerGap(552, Short.MAX_VALUE))
        );

        sidebarPanel.setBackground(new java.awt.Color(0, 0, 102));

        profileHeader.setBackground(new java.awt.Color(0, 0, 102));

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (1).png"))); // NOI18N
        userIcon.setText("jLabel1");

        usernameText.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        usernameText.setForeground(new java.awt.Color(255, 255, 255));
        usernameText.setText("sarah_admin");

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log-out.png"))); // NOI18N
        logoutButton.setBorder(null);
        logoutButton.setBorderPainted(false);
        logoutButton.setContentAreaFilled(false);
        logoutButton.setFocusPainted(false);
        logoutButton.addActionListener(this::logoutButtonActionPerformed);

        javax.swing.GroupLayout profileHeaderLayout = new javax.swing.GroupLayout(profileHeader);
        profileHeader.setLayout(profileHeaderLayout);
        profileHeaderLayout.setHorizontalGroup(
            profileHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(profileHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameText)
                    .addComponent(userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        profileHeaderLayout.setVerticalGroup(
            profileHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profileHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profileHeaderLayout.createSequentialGroup()
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(113, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profileHeaderLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(usernameText))))
        );

        navItem01.setBackground(new java.awt.Color(0, 0, 102));
        navItem01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navItem01MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navItem01MouseExited(evt);
            }
        });

        navItemText01.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        navItemText01.setForeground(new java.awt.Color(255, 255, 255));
        navItemText01.setText("Manage User Accounts");

        javax.swing.GroupLayout navItem01Layout = new javax.swing.GroupLayout(navItem01);
        navItem01.setLayout(navItem01Layout);
        navItem01Layout.setHorizontalGroup(
            navItem01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navItem01Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(navItemText01)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        navItem01Layout.setVerticalGroup(
            navItem01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navItem01Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(navItemText01)
                .addGap(19, 19, 19))
        );

        navItem02.setBackground(new java.awt.Color(0, 0, 102));
        navItem02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navItem02MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navItem02MouseExited(evt);
            }
        });

        navItemText02.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        navItemText02.setForeground(new java.awt.Color(255, 255, 255));
        navItemText02.setText("Manage Staff Roster");

        javax.swing.GroupLayout navItem02Layout = new javax.swing.GroupLayout(navItem02);
        navItem02.setLayout(navItem02Layout);
        navItem02Layout.setHorizontalGroup(
            navItem02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navItem02Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(navItemText02)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navItem02Layout.setVerticalGroup(
            navItem02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navItem02Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(navItemText02)
                .addGap(20, 20, 20))
        );

        navItem03.setBackground(new java.awt.Color(0, 0, 102));
        navItem03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navItem03MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navItem03MouseExited(evt);
            }
        });

        navItemText03.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        navItemText03.setForeground(new java.awt.Color(255, 255, 255));
        navItemText03.setText("Appointment Statistics");

        javax.swing.GroupLayout navItem03Layout = new javax.swing.GroupLayout(navItem03);
        navItem03.setLayout(navItem03Layout);
        navItem03Layout.setHorizontalGroup(
            navItem03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navItem03Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(navItemText03)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navItem03Layout.setVerticalGroup(
            navItem03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navItem03Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(navItemText03)
                .addGap(18, 18, 18))
        );

        navItem04.setBackground(new java.awt.Color(0, 0, 102));
        navItem04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navItem04MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navItem04MouseExited(evt);
            }
        });

        navItemText04.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        navItemText04.setForeground(new java.awt.Color(255, 255, 255));
        navItemText04.setText("Generate Report");

        javax.swing.GroupLayout navItem04Layout = new javax.swing.GroupLayout(navItem04);
        navItem04.setLayout(navItem04Layout);
        navItem04Layout.setHorizontalGroup(
            navItem04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navItem04Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(navItemText04)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navItem04Layout.setVerticalGroup(
            navItem04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navItem04Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(navItemText04)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navItem01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navItem02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navItem03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navItem04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(profileHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addComponent(profileHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(navItem01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navItem02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navItem03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navItem04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        

    private void navItem01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem01MouseEntered
        // TODO add your handling code here:
        navItem01.setBackground(Color.orange);
        navItemText01.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_navItem01MouseEntered

    private void navItem01MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem01MouseExited
        // TODO add your handling code here:
        navItem01.setBackground(new Color(0,0,102));
        navItemText01.setForeground(Color.WHITE);
    }//GEN-LAST:event_navItem01MouseExited

    private void navItem02MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem02MouseEntered
        // TODO add your handling code here:
        navItem02.setBackground(Color.orange);
        navItemText02.setForeground(Color.BLACK);
    }//GEN-LAST:event_navItem02MouseEntered

    private void navItem02MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem02MouseExited
        // TODO add your handling code here:
        navItem02.setBackground(new Color(0,0,102));
        navItemText02.setForeground(Color.WHITE);
    }//GEN-LAST:event_navItem02MouseExited

    private void navItem03MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem03MouseEntered
        // TODO add your handling code here:
        navItem03.setBackground(Color.orange);
        navItemText03.setForeground(Color.BLACK);
    }//GEN-LAST:event_navItem03MouseEntered

    private void navItem03MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem03MouseExited
        // TODO add your handling code here:
        navItem03.setBackground(new Color(0,0,102));
        navItemText03.setForeground(Color.WHITE);
    }//GEN-LAST:event_navItem03MouseExited

    private void navItem04MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem04MouseEntered
        // TODO add your handling code here:
        navItem04.setBackground(Color.orange);
        navItemText04.setForeground(Color.BLACK);
    }//GEN-LAST:event_navItem04MouseEntered

    private void navItem04MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem04MouseExited
        // TODO add your handling code here:
        navItem04.setBackground(new Color(0,0,102));
        navItemText04.setForeground(Color.WHITE);
    }//GEN-LAST:event_navItem04MouseExited

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void FullNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FullNameTFActionPerformed

    private void OffTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OffTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OffTFActionPerformed

    private void editInfoButton03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editInfoButton03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editInfoButton03ActionPerformed

    private void editInfoButton05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editInfoButton05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editInfoButton05ActionPerformed

    private void editInfoButton04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editInfoButton04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editInfoButton04ActionPerformed

    private void editInfoButton01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editInfoButton01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editInfoButton01ActionPerformed

    private void EmailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTFActionPerformed

    private void UsernameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTFActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(() -> new AdminMainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ContactTF;
    private javax.swing.JTextField EmailTF;
    private javax.swing.JTextField FullNameTF;
    private javax.swing.JTextField OffTF;
    private javax.swing.JTextField UsernameTF;
    private javax.swing.JLabel adminPageUserIcon;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton editInfoButton01;
    private javax.swing.JButton editInfoButton02;
    private javax.swing.JButton editInfoButton03;
    private javax.swing.JButton editInfoButton04;
    private javax.swing.JButton editInfoButton05;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel navItem01;
    private javax.swing.JPanel navItem02;
    private javax.swing.JPanel navItem03;
    private javax.swing.JPanel navItem04;
    private javax.swing.JLabel navItemText01;
    private javax.swing.JLabel navItemText02;
    private javax.swing.JLabel navItemText03;
    private javax.swing.JLabel navItemText04;
    private javax.swing.JLabel personalInformationTitle;
    private javax.swing.JPanel profileHeader;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JLabel userIcon;
    private javax.swing.JLabel usernameText;
    // End of variables declaration//GEN-END:variables
}
