/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package counselormgmtsystem.GUIprogram.StudentFrames;

import counselormgmtsystem.*;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author thesupreme
 */
public class StudentMainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentMainFrame.class.getName());
    private Student currentStudent;
    /**
     * Creates new form MainFrame
     */
    public StudentMainFrame(Student student) {
        this.currentStudent = student;
        initComponents();
        ImageIcon originalUserIcon = new ImageIcon(getClass().getResource("/images/user (1).png"));
        usernameText.setText(currentStudent.getUsername());
        Image rawUserImage = originalUserIcon.getImage();
        Image resizedUserImage = rawUserImage.getScaledInstance(80, 80, Image.SCALE_SMOOTH);
        userIcon.setIcon(new ImageIcon(resizedUserImage));
        logoutButton.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log-out.png")).getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH)));
        logoutButton.addActionListener(e -> {
            LoginFrame loginFrame = new LoginFrame();
            loginFrame.setVisible(true);
            this.dispose();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        contentPanel = new javax.swing.JPanel();
        sidebarPanel = new javax.swing.JPanel();
        profileHeader = new javax.swing.JPanel();
        userIcon = new javax.swing.JLabel();
        usernameText = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        navItem01 = new javax.swing.JPanel();
        navItemText01 = new javax.swing.JLabel();
        navItem02 = new javax.swing.JPanel();
        navItemText02 = new javax.swing.JLabel();
        navItem03 = new javax.swing.JPanel();
        navItemText03 = new javax.swing.JLabel();
        navItem04 = new javax.swing.JPanel();
        navItemText04 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );

        sidebarPanel.setBackground(new java.awt.Color(0, 0, 102));

        profileHeader.setBackground(new java.awt.Color(0, 0, 102));

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (1).png"))); // NOI18N
        userIcon.setText("jLabel1");

        usernameText.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        usernameText.setForeground(new java.awt.Color(255, 255, 255));
        usernameText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameText.setText("sarah_student");

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log-out.png"))); // NOI18N
        logoutButton.setBorder(null);
        logoutButton.setBorderPainted(false);
        logoutButton.setContentAreaFilled(false);
        logoutButton.setFocusPainted(false);
        logoutButton.addActionListener(this::logoutButtonActionPerformed);

        javax.swing.GroupLayout profileHeaderLayout = new javax.swing.GroupLayout(profileHeader);
        profileHeader.setLayout(profileHeaderLayout);
        profileHeaderLayout.setHorizontalGroup(
            profileHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
            .addComponent(usernameText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        profileHeaderLayout.setVerticalGroup(
            profileHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileHeaderLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usernameText)
                .addGap(17, 17, 17))
            .addGroup(profileHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        navItem01.setBackground(new java.awt.Color(0, 0, 102));
        navItem01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navItem01MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navItem01MouseExited(evt);
            }
        });

        navItemText01.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        navItemText01.setForeground(new java.awt.Color(255, 255, 255));
        navItemText01.setText("View Queue Number");

        javax.swing.GroupLayout navItem01Layout = new javax.swing.GroupLayout(navItem01);
        navItem01.setLayout(navItem01Layout);
        navItem01Layout.setHorizontalGroup(
            navItem01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navItem01Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(navItemText01)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navItem01Layout.setVerticalGroup(
            navItem01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navItem01Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(navItemText01)
                .addGap(20, 20, 20))
        );

        navItem02.setBackground(new java.awt.Color(0, 0, 102));
        navItem02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navItem02MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navItem02MouseExited(evt);
            }
        });

        navItemText02.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        navItemText02.setForeground(new java.awt.Color(255, 255, 255));
        navItemText02.setText("<html>Manage Counseling Appointments</html>");

        javax.swing.GroupLayout navItem02Layout = new javax.swing.GroupLayout(navItem02);
        navItem02.setLayout(navItem02Layout);
        navItem02Layout.setHorizontalGroup(
            navItem02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navItem02Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(navItemText02, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        navItem02Layout.setVerticalGroup(
            navItem02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navItem02Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(navItemText02, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        navItem03.setBackground(new java.awt.Color(0, 0, 102));
        navItem03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navItem03MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navItem03MouseExited(evt);
            }
        });

        navItemText03.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        navItemText03.setForeground(new java.awt.Color(255, 255, 255));
        navItemText03.setText("View appointment history");

        javax.swing.GroupLayout navItem03Layout = new javax.swing.GroupLayout(navItem03);
        navItem03.setLayout(navItem03Layout);
        navItem03Layout.setHorizontalGroup(
            navItem03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navItem03Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(navItemText03)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navItem03Layout.setVerticalGroup(
            navItem03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navItem03Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(navItemText03)
                .addGap(18, 18, 18))
        );

        navItem04.setBackground(new java.awt.Color(0, 0, 102));
        navItem04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navItem04MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navItem04MouseExited(evt);
            }
        });

        navItemText04.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        navItemText04.setForeground(new java.awt.Color(255, 255, 255));
        navItemText04.setText("View counselor profiles");

        javax.swing.GroupLayout navItem04Layout = new javax.swing.GroupLayout(navItem04);
        navItem04.setLayout(navItem04Layout);
        navItem04Layout.setHorizontalGroup(
            navItem04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navItem04Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(navItemText04)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navItem04Layout.setVerticalGroup(
            navItem04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navItem04Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(navItemText04)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navItem01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navItem02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navItem03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navItem04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(profileHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addComponent(profileHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(navItem01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navItem02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navItem03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navItem04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void navItem01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem01MouseEntered
        // TODO add your handling code here:
        navItem01.setBackground(Color.orange);
        navItemText01.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_navItem01MouseEntered

    private void navItem01MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem01MouseExited
        // TODO add your handling code here:
        navItem01.setBackground(new Color(0,0,102));
        navItemText01.setForeground(Color.WHITE);
    }//GEN-LAST:event_navItem01MouseExited

    private void navItem02MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem02MouseEntered
        // TODO add your handling code here:
        navItem02.setBackground(Color.orange);
        navItemText02.setForeground(Color.BLACK);
    }//GEN-LAST:event_navItem02MouseEntered

    private void navItem02MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem02MouseExited
        // TODO add your handling code here:
        navItem02.setBackground(new Color(0,0,102));
        navItemText02.setForeground(Color.WHITE);
    }//GEN-LAST:event_navItem02MouseExited

    private void navItem03MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem03MouseEntered
        // TODO add your handling code here:
        navItem03.setBackground(Color.orange);
        navItemText03.setForeground(Color.BLACK);
    }//GEN-LAST:event_navItem03MouseEntered

    private void navItem03MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem03MouseExited
        // TODO add your handling code here:
        navItem03.setBackground(new Color(0,0,102));
        navItemText03.setForeground(Color.WHITE);
    }//GEN-LAST:event_navItem03MouseExited

    private void navItem04MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem04MouseEntered
        // TODO add your handling code here:
        navItem04.setBackground(Color.orange);
        navItemText04.setForeground(Color.BLACK);
    }//GEN-LAST:event_navItem04MouseEntered

    private void navItem04MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navItem04MouseExited
        // TODO add your handling code here:
        navItem04.setBackground(new Color(0,0,102));
        navItemText04.setForeground(Color.WHITE);
    }//GEN-LAST:event_navItem04MouseExited

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutButtonActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel navItem01;
    private javax.swing.JPanel navItem02;
    private javax.swing.JPanel navItem03;
    private javax.swing.JPanel navItem04;
    private javax.swing.JLabel navItemText01;
    private javax.swing.JLabel navItemText02;
    private javax.swing.JLabel navItemText03;
    private javax.swing.JLabel navItemText04;
    private javax.swing.JPanel profileHeader;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JLabel userIcon;
    private javax.swing.JLabel usernameText;
    // End of variables declaration//GEN-END:variables
}
